ccflags-y += -D DONGLE_CABLE_INSERT=1
ccflags-y += -D QUICK_CHARGE_SUPPORT
obj-$(CONFIG_ANALOGIX_OHIO) += anx_ohio_driver.o anx_ohio_private_interface.o anx_ohio_public_interface.o usb_typec_fw_update.o
ohio-objs := anx_ohio_driver.o anx_ohio_private_interface.o anx_ohio_public_interface.o usb_typec_fw_update.o
