ifdef CONFIG_HTC_DEBUG
obj-$(CONFIG_HTC_DEBUG) += htc_debug_tools.o
obj-$(CONFIG_HTC_HELPER_FUNCTIONS) += helper_funcs.o
obj-$(CONFIG_HTC_REBOOT_BLOCK) += htc_reboot_block.o
obj-$(CONFIG_HTC_DEBUG_RAMOOPS) += htc_ramoops.o
obj-$(CONFIG_HTC_DEBUG_PAGE_USER_TRACE) += debug_page_user_trace.o
obj-$(CONFIG_HTC_DEBUG_BOOTLOADER_LOG) += htc_bootloader_log.o
obj-$(CONFIG_HTC_NC_GPIO_PIN_SETTING)  += htc_nc_setting.o
obj-$(CONFIG_HTC_DEBUG_SAVE_BOOT_MSG) += bootmsg.o
obj-$(CONFIG_HTC_PROCESS_DEBUG) += htc_process_debug.o
obj-$(CONFIG_HTC_DEBUG_RESTART_TIMER) += htc_restart_timer_notifier.o
endif
