ifdef CONFIG_HTC_DEBUG
obj-$(CONFIG_HTC_DEBUG) += htc_debug_tools.o
obj-$(CONFIG_HTC_HELPER_FUNCTIONS) += helper_funcs.o
obj-$(CONFIG_HTC_REBOOT_BLOCK) += htc_reboot_block.o
obj-$(CONFIG_HTC_DEBUG_RAMOOPS) += htc_ramoops.o
obj-$(CONFIG_HTC_DEBUG_SAVE_BOOT_MSG) += bootmsg.o
endif
